"""Explicit reviewed temporary zero-network test nodes."""
from __future__ import annotations

TEMP_ONLY = frozenset({
    'tests/test_agent_display.py::test_reported_helper_is_sticky_self_only_and_keeps_capabilities',
    'tests/test_agent_display.py::test_unknown_sessions_are_distinct_and_ordinals_survive_revoke_and_device_label_changes',
    'tests/test_agent_display.py::test_authenticated_child_cannot_promote_and_labels_do_not_grant_main_status',
    'tests/test_agent_display.py::test_readable_family_uses_recorded_model_not_harness_or_auth_id',
    'tests/test_agent_display.py::test_same_family_native_sessions_get_distinct_stable_ordinals',
    'tests/test_agent_display.py::test_unknown_ordinals_do_not_collide_after_device_metadata_arrives',
    'tests/test_agent_display.py::test_revoked_main_is_ineligible',
    'tests/test_agent_display.py::test_presented_agents_children_and_internal_senders_are_read_only',
    'tests/test_agent_display.py::test_display_suffix_uses_complete_identity_and_retained_collision_peers',
    'tests/test_agent_display.py::test_child_display_marks_inherited_model_without_changing_authority',

    'tests/test_notification_performance.py::test_reader_authenticates_once_and_notifies_before_checkpoint',
    'tests/test_notification_performance.py::test_unchanged_checkpoint_avoids_graph_rewrite',
    'tests/test_notification_performance.py::test_changed_checkpoint_preserves_bound_owner_and_label',
    'tests/test_notification_performance.py::test_urgent_action_survives_host_context_limit',
    'tests/test_notification_reader.py::test_hook_session_selects_each_root_without_environment_fallback',
    'tests/test_notification_reader.py::test_unbound_child_never_reads_default_or_parent_inbox',
    'tests/test_notification_reader.py::test_explicit_launcher_parent_requires_saved_binding',
    'tests/test_notification_reader.py::test_legacy_root_requires_its_exact_saved_principal_without_thread_namespace',
    'tests/test_notification_reader.py::test_local_launcher_alias_resolves_only_its_exact_saved_actor',
    'tests/test_notification_reader.py::test_authenticated_context_reuses_reader_without_discovery_or_reauthentication',
    'tests/test_notification_reader.py::test_saved_slot_authority_tampering_is_refused',
    'tests/test_notification_reader.py::test_reader_uses_existing_token_and_authenticates_before_nudge',
    'tests/test_notification_reader.py::test_revoked_or_wrong_capability_never_reads',
    'tests/test_notification_reader.py::test_nudge_subprocess_is_bounded_and_session_explicit',
    'tests/test_notification_reader.py::test_unbound_notification_does_not_block_completed_tools',
    'tests/test_notification_reader.py::test_explicit_parent_hook_preserves_launcher_root',
    'tests/test_notification_reader.py::test_checkout_authority_mismatch_is_refused',
    'tests/test_notification_reader.py::test_sibling_project_identity_mismatch_is_refused',
    'tests/test_harness_hook_outages.py::test_post_outage_does_not_reverse_a_completed_tool',
    'tests/test_harness_hook_outages.py::test_stop_remains_blocked_when_authority_is_unavailable',
    'tests/test_harness_hook_outages.py::test_pre_outage_is_a_structured_denial_with_a_reason',
    'tests/test_harness_hook_outages.py::test_post_checkpoint_outage_preserves_pending_message_alert',
    'tests/test_harness_hook_outages.py::test_post_lifecycle_failure_preserves_stop_message_alert',
    'tests/test_hook_failure_records.py::test_nudge_failure_keeps_reference_visible_in_post_context',
    'tests/test_native_parent_handoff.py::test_parent_hook_automatically_prebinds_child_and_child_uses_only_own_token',
    'tests/test_notification_performance.py::test_denied_descendant_inspection_still_cancels_and_reaps_owned_reader',

    'tests/test_automatic_project_connection.py::test_native_profile_ack_is_required_on_legacy_cache_and_harness_only_updates',
    'tests/test_automatic_project_connection.py::test_native_profile_forged_ack_cannot_cache_success',
    'tests/test_automatic_project_connection.py::test_native_profile_reports_device_when_session_model_is_unknown',
    'tests/test_automatic_project_connection.py::test_native_child_profile_uses_exact_saved_child_and_parent_device',
    'tests/test_workspace_device_metadata.py::test_own_profile_updates_child_harness_without_promoting_or_changing_model',
    'tests/test_workspace_device_metadata.py::test_own_profile_report_is_atomic_when_verified_harness_refuses_change',
    'tests/test_kernel_role_home.py::test_loader_omits_only_the_verified_first_self_install_name',
    'tests/test_kernel_role_home.py::test_loader_refuses_unverified_or_changed_install_name',
    'tests/test_workspace_device_metadata.py::test_child_missing_profile_derives_parent_facts_without_registry_writes',
    'tests/test_workspace_device_metadata.py::test_child_own_profile_wins_and_caller_cannot_forge_inheritance',
    'tests/test_workspace_device_metadata.py::test_unknown_profile_is_nonempty_and_missing_parent_does_not_invent_device',
    'tests/test_workspace_device_metadata.py::test_device_metadata_is_visible_and_delegates_inherit_without_changing_rights',
    'tests/test_workspace_device_metadata.py::test_agent_device_report_cannot_claim_paired_authority_or_change_another_actor',
    'tests/test_workspace_device_metadata.py::test_malformed_or_unproved_device_metadata_is_rejected',
    'tests/test_kernel_role_home.py::test_smoke_initial_capture_failure_never_releases_gate',
    'tests/test_kernel_role_home.py::test_smoke_changed_generation_never_signals_group',
    'tests/test_kernel_role_home.py::test_smoke_unknown_membership_never_signals_or_claims_cleanup',
    'tests/test_serve_no_bypass.py::test_denied_process_observation_preserves_broker_dispatch_and_refusal',
    'tests/test_source_snapshot_guards.py::test_actual_git_refuses_hostile_asset',
    'tests/test_source_snapshot_guards.py::test_actual_git_uses_owned_fixed_asset_without_inherited_path',

    'tests/test_profilehook.py::test_helper_sessions_have_separate_stable_namespace_without_actor_selection',
    'tests/test_profilehook.py::test_hook_metadata_whitelist_does_not_read_content_or_guess_settings',
    'tests/test_profilehook.py::test_malformed_metadata_is_rejected_before_transport',
    'tests/test_profilehook.py::test_optional_session_model_and_switched_model_are_event_reports_only',
    'tests/test_serve_no_bypass.py::test_a_backend_is_only_started_by_the_manager',
    'tests/test_serve_no_bypass.py::test_a_broker_is_only_built_where_the_machines_is_chosen',
    'tests/test_serve_no_bypass.py::test_a_connection_to_a_server_goes_through_the_request_queue',
    'tests/test_serve_no_bypass.py::test_a_manager_that_keeps_the_machines_records_uses_the_machines_broker',
    'tests/test_serve_no_bypass.py::test_a_server_process_is_only_launched_by_a_backend_holding_a_lease',
    'tests/test_serve_no_bypass.py::test_every_public_entry_of_the_manager_reaches_the_broker',
    'tests/test_serve_no_bypass.py::test_no_flag_to_lease_skips_the_broker',
    'tests/test_serve_no_bypass.py::test_only_the_known_modules_start_a_process_and_name_the_server_binary',
    'tests/test_serve_no_bypass.py::test_the_grant_is_only_opened_by_the_broker',
    'tests/test_serve_no_bypass.py::test_the_private_starts_are_only_reached_by_the_manager_and_the_broker',
    'tests/test_serve_no_bypass.py::test_the_proof_a_backend_needs_is_only_made_by_the_manager',
    'tests/test_serve_no_bypass.py::test_the_up_command_reaches_a_server_only_through_a_lease',
    'tests/test_wiring.py::test_piece_is_wired_in',
    'tests/test_wiring.py::test_standalone_names_only_real_pieces',

    'tests/test_profilehook.py::test_observer_runtime_metadata_requires_matching_installed_module_and_full_commit',
    'tests/test_task_native_execution.py::test_native_commands_import_in_fresh_interpreter',
    'tests/test_task_native_execution.py::test_typed_native_prepare_dispatches_exact_authenticated_request',

    'tests/test_profilehook.py::test_observation_modules_import_in_fresh_interpreter',
    'tests/test_profilehook.py::test_notification_failure_never_blocks_and_redacts_credentials',
    'tests/test_profilehook.py::test_notification_parser_is_bounded_and_fails_open',
    'tests/test_profilehook.py::test_metadata_authentication_preserves_actor_and_separates_helper_observations',
    'tests/test_profilehook.py::test_launcher_observation_preserves_requests_without_inventing_effective_limits',
    'tests/test_profilehook.py::test_local_launcher_observation_keeps_its_established_workspace_authority',

    'tests/test_source_snapshot_guards.py::test_spoofed_home_preserves_actual_account_roots_and_explicit_overrides',
    'tests/test_source_snapshot_guards.py::test_partial_snapshot_construction_removes_its_private_metadata',
    'tests/test_source_snapshot_guards.py::test_git_inventory_launch_excludes_inherited_configuration_and_input',

    'tests/test_broker_idle_persistence.py::test_idle_reaping_preserves_original_durable_inode_and_holder_profile',
    'tests/test_broker_idle_persistence.py::test_dirty_persistence_failure_keeps_old_record_and_retries',
    'tests/test_broker_idle_persistence.py::test_external_durable_record_change_is_repaired_without_cache_shortcut',
    'tests/test_broker_idle_persistence.py::test_redirected_or_hardlinked_record_is_never_accepted_as_unchanged',
    'tests/test_broker_idle_persistence.py::test_unchanged_transferred_records_still_check_authority',
    'tests/test_broker_idle_persistence.py::test_handoff_checkpoint_skips_only_unchanged_authorized_release_state',

    'tests/test_native_session_metadata.py::test_exact_own_row_reports_helper_and_exact_model_without_parent_authority',
    'tests/test_native_session_metadata.py::test_redirected_storage_is_refused_without_following_it',
    'tests/test_native_session_metadata.py::test_writable_or_foreign_storage_and_database_bounds_are_refused',
    'tests/test_native_session_metadata.py::test_conflicting_generic_session_cannot_select_another_native_thread',

    'tests/test_immutable_compute_generations.py::test_generation_verifier_pins_interpreter_and_sanitizes_hostile_environment',
    'tests/test_task_coordination_grants.py::test_creation_before_main_persists_consent_and_later_materializes_exact_main',
    'tests/test_task_coordination_grants.py::test_materialization_replay_is_idempotent',
    'tests/test_task_coordination_grants.py::test_creator_revocation_prevents_later_materialization',
    'tests/test_task_coordination_grants.py::test_creator_project_loss_prevents_later_materialization',
    'tests/test_task_coordination_grants.py::test_creator_revokes_intent_and_all_derived_grants',
    'tests/test_task_coordination_grants.py::test_foreign_main_cannot_delegate_or_revoke_creators_task',
    'tests/test_task_coordination_grants.py::test_stale_or_reselected_main_cannot_admit_new_work',
    'tests/test_task_coordination_grants.py::test_registered_child_uses_only_its_selected_parents_exact_grant',
    'tests/test_task_coordination_grants.py::test_expired_intent_cannot_materialize',
    'tests/test_task_coordination_grants.py::test_explicit_replay_cannot_expand_review_permission_or_expiry',
    'tests/test_task_coordination_grants.py::test_actual_claimed_worker_can_checkpoint_through_main_reselection',
    'tests/test_task_coordination_grants.py::test_actual_claimed_worker_survives_main_presence_staleness',
    'tests/test_task_coordination_grants.py::test_actual_claimed_worker_cannot_continue_after_creator_revokes_intent',
    'tests/test_task_coordination_grants.py::test_creator_can_independently_review_other_mains_actual_proposal',
    'tests/test_task_coordination_grants.py::test_grant_never_allows_worker_self_review',
    'tests/test_task_coordination_grants.py::test_same_clock_creator_reenrollment_cannot_reuse_original_consent',
    'tests/test_task_coordination_grants.py::test_same_clock_main_reenrollment_cannot_consume_original_grant',
    'tests/test_task_coordination_grants.py::test_creator_explicitly_delegates_to_current_automatic_main',
    'tests/test_task_coordination_grants.py::test_creation_without_review_permission_never_grants_parent_review',
    'tests/test_task_coordination_grants.py::test_grant_review_preserves_same_economic_account_refusal',
    'tests/test_task_coordination_grants.py::test_typed_creation_rejects_nonboolean_review_consent',
    'tests/test_task_coordination_grants.py::test_typed_delegation_rejects_private_generation_and_unknown_control_fields',
    'tests/test_task_coordination_grants.py::test_child_creator_inherited_project_consent_precedes_later_main',
    'tests/test_task_coordination_grants.py::test_child_creator_root_project_loss_invalidates_materialization',

    'tests/test_immutable_compute_generations.py::test_private_compute_selection_does_not_change_global_selection',
    'tests/test_immutable_compute_generations.py::test_artifact_mismatch_leaves_compute_unbound',
    'tests/test_immutable_compute_generations.py::test_active_generation_refuses_direct_mutation',
    'tests/test_immutable_compute_generations.py::test_missing_sdk_dependency_is_not_bound_as_ready',
    'tests/test_immutable_compute_generations.py::test_library_change_builds_new_prefix_and_failure_preserves_selection',
    'tests/test_immutable_compute_generations.py::test_queued_job_keeps_durable_generation_after_restart',
    'tests/test_immutable_compute_generations.py::test_forged_compute_receipt_is_rejected',
    'tests/test_immutable_compute_generations.py::test_running_recovery_keeps_pin_without_importing_or_relaunching',
    'tests/test_immutable_compute_generations.py::test_legacy_queued_record_keeps_interpreter_environment',
    'tests/test_automatic_project_connection.py::test_native_metadata_uses_exact_binding_and_acknowledged_cache',
    'tests/test_automatic_project_connection.py::test_native_report_failure_does_not_cache_or_block_existing_capability',
    'tests/test_automatic_project_connection.py::test_native_observer_retry_model_revisions_and_private_generation',
    'tests/test_automatic_project_connection.py::test_native_observer_refuses_forged_ack_without_cache_success',
    'tests/test_automatic_project_connection.py::test_native_observer_missing_capability_never_enrolls',
    'tests/test_automatic_project_connection.py::test_native_observer_honors_expired_budget_and_parent_cancel',
    'tests/test_http_cancel.py::test_child_cancellation_preserves_parent_and_closes_shared_owned_sockets',
    'tests/test_http_cancel.py::test_parent_cancel_between_registration_and_child_binding_closes_socket',
    'tests/test_workspace_lock_deadline.py::test_lock_deadline_uncontended_and_default_keep_private_file',
    'tests/test_workspace_lock_deadline.py::test_contended_lock_deadline_expires_without_mutating_holder',
    'tests/test_workspace_lock_deadline.py::test_lock_deadline_releases_after_body_failure',
    'tests/test_workspace_lock_deadline.py::test_invalid_lock_deadline_is_refused_before_creating_storage',
    'tests/test_kernel_selector_admission.py::test_reviewed_nodes_preserve_complete_invocation_validation',
    'tests/test_kernel_selector_admission.py::test_unreviewed_files_and_resource_fixtures_remain_refused',
    'tests/test_task_coordinator.py::test_recent_explicit_selection_wins_without_polling_promoting_another_main',
    'tests/test_task_coordinator.py::test_delegated_revoked_stale_foreign_and_non_harness_sessions_are_not_candidates',
    'tests/test_task_coordinator.py::test_fallback_uses_independent_quality_then_explicit_model_preference_without_vendor_names',
    'tests/test_task_coordinator.py::test_explicit_main_selection_keeps_unknown_harness_unknown_and_requires_project_heartbeat',
    'tests/test_task_coordinator.py::test_created_task_ping_targets_exact_main_identity_once_even_for_creator',
    'tests/test_task_coordinator.py::test_bus_commit_before_notice_checkpoint_does_not_duplicate_on_retry',
    'tests/test_task_coordinator.py::test_delivery_failure_keeps_created_task_pending_and_needs_no_foreign_credentials',
    'tests/test_task_coordinator.py::test_cancelled_notice_is_not_delivered',
    'tests/test_task_coordinator.py::test_verified_lookup_failure_remains_pending_without_resend',
    'tests/test_task_coordinator.py::test_exact_message_lookup_binds_sender_recipient_subject_and_refuses_missing_verified_row',
    'tests/test_task_coordinator.py::test_typed_creation_and_poll_route_with_authenticated_host_presence',
    'tests/test_task_coordinator.py::test_host_presence_refuses_persisted_stale_or_foreign_activity',
    'tests/test_task_coordinator.py::test_poll_backfills_existing_unassigned_task_and_failed_delivery_retries',
    'tests/test_task_coordinator.py::test_sticky_helper_cannot_select_or_retain_coordination_but_unknown_main_can',
    'tests/test_task_coordinator.py::test_unselected_recent_main_receives_unassigned_task_with_unknown_quality',
    'tests/test_task_coordinator.py::test_automatic_selection_respects_explicit_main_and_internal_model_order',
    'tests/test_task_coordinator.py::test_automatic_selection_excludes_sticky_helpers_and_foreign_mains',
    'tests/test_task_coordinator.py::test_independent_model_sources_are_ranked_without_combining_samples',
    'tests/test_task_coordinator_fallback.py::test_sole_verified_loaded_model_launches_once_without_forwarding_caller_credential',
    'tests/test_task_coordinator_fallback.py::test_unavailable_or_unranked_models_preserve_pending_task_without_launch',
    'tests/test_task_coordinator_fallback.py::test_admission_failure_is_durable_and_retried_without_losing_task',
    'tests/test_task_coordinator_fallback.py::test_uncertain_launch_is_not_replayed_after_interruption',
    'tests/test_task_coordinator_fallback.py::test_revoked_foreign_or_inactive_admission_cannot_launch',
    'tests/test_task_coordinator_fallback.py::test_internal_launcher_rechecks_canonical_grant_without_forwarding_token',
    'tests/test_task_coordinator_fallback.py::test_existing_selected_live_main_is_not_replaced_with_a_model_worker',
    'tests/test_task_coordinator_fallback.py::test_internal_launcher_refuses_another_cluster_and_generic_person',
    'tests/test_task_coordinator_fallback.py::test_failed_attempted_spawn_is_not_replayed',
    'tests/test_task_coordinator_fallback.py::test_caller_orders_are_exactly_deduplicated_and_never_promote_greeter',
    'tests/test_task_coordinator_fallback.py::test_orders_refuse_ambiguous_receipt_and_reassigned_caller',
    'tests/test_task_coordinator_fallback.py::test_same_project_metadata_is_readable_without_creator_or_reviewer_escalation',
    'tests/test_task_coordinator_fallback.py::test_task_data_from_unknown_or_reassigned_creator_cannot_issue_delegated_orders',
    'tests/test_task_coordinator_fallback.py::test_person_creator_binding_and_revocation_remain_data_only',
    'tests/test_task_coordinator_fallback.py::test_existing_unselected_live_main_is_ranked_without_launching_model_worker',
    'tests/test_execution_profile.py::test_own_profile_fields_are_reported_and_unobserved_limits_unknown',
    'tests/test_execution_profile.py::test_observation_payload_cannot_select_identity_authority_or_content',
    'tests/test_execution_profile.py::test_profile_metadata_whitelist_rejects_malformed_values',
    'tests/test_execution_profile.py::test_profile_events_are_idempotent_bounded_and_cannot_be_rebound',
    'tests/test_execution_profile.py::test_child_observations_preserve_registry_parent_without_impersonation',
    'tests/test_execution_profile.py::test_revoked_agent_and_redirected_graph_are_refused',
    'tests/test_execution_profile.py::test_restricted_child_cannot_record_without_existing_send_right',
    'tests/test_execution_profile.py::test_expired_child_cannot_record_observations',
    'tests/test_execution_profile.py::test_observations_share_canonical_graph_without_replacing_agent_or_work_records',
    'tests/test_execution_profile.py::test_public_existing_storage_is_refused_without_chmod_or_write',
    'tests/test_execution_profile.py::test_redirected_graph_auxiliary_storage_is_refused_without_touching_target',
    'tests/test_execution_profile.py::test_redirected_and_writable_parent_storage_is_refused',
    'tests/test_execution_profile.py::test_foreign_parent_storage_is_refused',
    'tests/test_execution_profile.py::test_observation_generation_is_private_and_model_switch_clears_stale_facts',
    'tests/test_model_work_attribution.py::test_unknown_artifact_and_runtime_are_not_promoted_from_a_local_filename',
})

RESOURCE_NODES = frozenset({
    'tests/test_kernel_role_home.py::test_fixed_normal_role_imports_and_runtime_verification',
    'tests/test_kernel_role_home.py::test_owned_smoke_reaps_exited_leader_and_known_stdout_child',
    'tests/test_kernel_role_home.py::test_role_home_atomic_state_and_immutable_fences',
})


def admitted_node(selector: str) -> bool:
    if selector in TEMP_ONLY | RESOURCE_NODES:
        return True
    base, separator, suffix = selector.partition("[")
    return bool(separator and suffix.endswith("]") and "::" not in suffix and base in TEMP_ONLY)
