"""The array API the backend-neutral math is written against."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

Tensor = Any


@runtime_checkable
class ArrayOps(Protocol):
    """Array operations the backend-neutral math may use."""

    int32: Any
    int64: Any
    float32: Any

    # Factories
    def array(self, value: Any, dtype: Any = None) -> Tensor: ...
    def zeros(self, shape: tuple[int, ...], dtype: Any = None) -> Tensor: ...
    def ones(self, shape: tuple[int, ...], dtype: Any = None) -> Tensor: ...
    def zeros_like(self, ref: Tensor) -> Tensor: ...
    def ones_like(self, ref: Tensor) -> Tensor: ...
    def arange(self, *args: Any, dtype: Any = None) -> Tensor: ...
    def eye(self, n: int) -> Tensor: ...

    # Shape
    def reshape(self, x: Tensor, shape: tuple[int, ...]) -> Tensor: ...
    def stack(self, values: list[Tensor], axis: int = 0) -> Tensor: ...
    def concatenate(self, values: list[Tensor], axis: int = -1) -> Tensor: ...
    def tile(self, value: Tensor, reps: tuple[int, ...]) -> Tensor: ...
    def broadcast_to(self, x: Tensor, shape: tuple[int, ...]) -> Tensor: ...
    def swapaxes(self, x: Tensor, axis1: int, axis2: int) -> Tensor: ...

    # Indexing
    def take(self, x: Tensor, index: Tensor, axis: int = 0) -> Tensor: ...
    def argsort(self, x: Tensor, axis: int = -1) -> Tensor: ...
    def argmin(self, x: Tensor, axis: int = -1) -> Tensor: ...
    def take_along_axis(self, x: Tensor, indices: Tensor, axis: int = -1) -> Tensor: ...
    def where(self, condition: Tensor, a: Tensor, b: Tensor) -> Tensor: ...

    # Autograd boundary
    def stop_gradient(self, value: Tensor) -> Tensor: ...

    # Elementwise
    def sigmoid(self, value: Tensor) -> Tensor: ...
    def tanh(self, value: Tensor) -> Tensor: ...
    def sin(self, value: Tensor) -> Tensor: ...
    def cos(self, value: Tensor) -> Tensor: ...
    def sqrt(self, value: Tensor) -> Tensor: ...
    def rsqrt(self, value: Tensor) -> Tensor: ...
    def erf(self, value: Tensor) -> Tensor: ...
    def exp(self, value: Tensor) -> Tensor: ...
    def log(self, value: Tensor) -> Tensor: ...
    def log1p(self, value: Tensor) -> Tensor: ...
    def reciprocal(self, value: Tensor) -> Tensor: ...
    def abs(self, value: Tensor) -> Tensor: ...
    def floor(self, value: Tensor) -> Tensor: ...
    def round(self, value: Tensor) -> Tensor: ...
    def clip(self, value: Tensor, min_value: float, max_value: float) -> Tensor: ...
    def maximum(self, a: Tensor, b: Tensor) -> Tensor: ...
    def minimum(self, a: Tensor, b: Tensor) -> Tensor: ...
    def nan_to_num(self, value: Tensor) -> Tensor: ...

    # Linear algebra
    def matmul(self, a: Tensor, b: Tensor) -> Tensor: ...
    def softmax(self, value: Tensor, axis: int = -1) -> Tensor: ...
    def einsum(self, spec: str, *operands: Tensor) -> Tensor: ...
    def repeat(self, x: Tensor, repeats: int, axis: int) -> Tensor: ...

    # Reductions
    def sum(self, value: Tensor, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
    def mean(self, value: Tensor, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
    def max(self, value: Tensor, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
    def min(self, value: Tensor, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
    def logsumexp(self, value: Tensor, axis: int = -1) -> Tensor: ...


@dataclass
class ArrayBackend:
    """One framework's implementation of everything the shared math needs."""

    name: str
    """``"mlx"`` or ``"torch"``. Used in error messages and parity reports."""

    ops: ArrayOps
    scatter_add: Callable[..., Tensor]
    segment_sum: Callable[..., Tensor]
    make_linear: Callable[[int, int], Any]
    cumsum: Callable[..., Tensor]
    cumprod: Callable[..., Tensor]
    rfft_abs: Callable[..., Tensor]
    """Magnitude spectrum of a real FFT: ``(x, axis) -> |rfft(x)|``."""

    accel: object | None = None
    """Optional framework-specific accelerator handle. Shared math must not read it."""


def bind_device(backend: ArrayBackend, reference: Tensor) -> None:
    """Point the backend's factories at ``reference``'s device, if it has one."""
    binder = getattr(backend.ops, "bind_device", None)
    if callable(binder):
        binder(reference)
