"""The other machines on this LAN, and how to run work on them."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_WHERE = {
    "BENCH_KIND": "calibration",
    "calibrate": "calibration",
    "measure": "calibration",
    "ChatError": "chat",
    "Target": "chat",
    "targets": "chat",
    "Conversation": "conversations",
    "Conversations": "conversations",
    "Message": "conversations",
    "Daemon": "api",
    "make_handler": "api",
    "load_or_create_token": "daemon",
    "serve_forever": "daemon",
    "REPORT_GROUP": "device",
    "device_report": "device",
    "registered_reports": "device",
    "resolve_report": "device",
    "stdlib_device_report": "device",
    "safe_relpath": "files",
    "DaemonError": "jobs",
    "Job": "jobs",
    "JobRunner": "jobs",
    "Advertiser": "discovery",
    "Beacon": "discovery",
    "DEFAULT_CLUSTER": "discovery",
    "DiscoveryError": "discovery",
    "MIN_PASSPHRASE": "discovery",
    "cluster_group": "discovery",
    "create_cluster_key": "discovery",
    "derive_token": "discovery",
    "discover": "discovery",
    "group_path": "discovery",
    "in_cluster": "discovery",
    "join_by_passphrase": "onboard.joining",
    "key_path": "discovery",
    "load_cluster_key": "discovery",
    "Suggestion": "catalogue",
    "families": "catalogue",
    "family_of": "catalogue",
    "how_many": "catalogue",
    "is_unfiltered": "catalogue",
    "popular": "catalogue",
    "searched_count": "catalogue",
    "searched_families": "catalogue",
    "suggestions": "catalogue",
    "Downloads": "models",
    "Getting": "models",
    "Model": "models",
    "Models": "models",
    "draft_beside": "models",
    "ModelError": "weights",
    "resolve": "weights",
    "Candidate": "pool",
    "Requires": "pool",
    "Score": "pool",
    "candidates": "pool",
    "choose": "pool",
    "eligible": "pool",
    "soonest": "pool",
    "Rates": "rates",
    "Peer": "remote",
    "PeerError": "remote",
    "Endpoint": "serving",
    "Served": "serving",
    "Serving": "serving",
    "discover_serving": "serving",
    "Placement": "work",
    "Unit": "work",
    "run": "work",
}

__all__ = [
    'BENCH_KIND',
    'DEFAULT_CLUSTER',
    'MIN_PASSPHRASE',
    'REPORT_GROUP',
    'Advertiser',
    'Beacon',
    'Candidate',
    'ChatError',
    'Conversation',
    'Conversations',
    'Daemon',
    'DaemonError',
    'DiscoveryError',
    'Downloads',
    'Endpoint',
    'Getting',
    'Job',
    'JobRunner',
    'Message',
    'Model',
    'ModelError',
    'Models',
    'Peer',
    'PeerError',
    'Placement',
    'Rates',
    'Requires',
    'Score',
    'Served',
    'Serving',
    'Suggestion',
    'Target',
    'Unit',
    'calibrate',
    'candidates',
    'check_passphrase',
    'choose',
    'cluster_group',
    'create_cluster_key',
    'derive_token',
    'device_report',
    'discover',
    'discover_serving',
    'draft_beside',
    'eligible',
    'families',
    'family_of',
    'group_path',
    'how_many',
    'in_cluster',
    'is_unfiltered',
    'join_cluster',
    'key_from_passphrase',
    'key_path',
    'load_cluster_key',
    'load_or_create_token',
    'make_handler',
    'measure',
    'popular',
    'registered_reports',
    'resolve',
    'resolve_report',
    'run',
    'safe_relpath',
    'searched_count',
    'searched_families',
    'serve_forever',
    'soonest',
    'stdlib_device_report',
    'suggestions',
    'targets',
]


def __getattr__(name: str) -> Any:
    """The named export, loading the submodule that defines it."""
    where = _WHERE.get(name)
    if where is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f"{__name__}.{where}"), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(__all__) | set(globals()))
