"""The other machines on this LAN, and how to run work on them."""

from __future__ import annotations

from ml_stack.fleet.daemon import (
    REPORT_GROUP,
    DaemonError,
    Job,
    JobRunner,
    device_report,
    load_or_create_token,
    make_handler,
    registered_reports,
    resolve_report,
    safe_relpath,
    serve_forever,
    stdlib_device_report,
)
from ml_stack.fleet.discovery import (
    Advertiser,
    Beacon,
    DiscoveryError,
    MIN_PASSPHRASE,
    create_cluster_key,
    derive_token,
    discover,
    check_passphrase,
    cluster_group,
    group_path,
    in_cluster,
    join_cluster,
    key_from_passphrase,
    key_path,
    load_cluster_key,
)
from ml_stack.fleet.bench import BENCH_KIND, calibrate, measure
from ml_stack.fleet.pool import (
    Candidate,
    Requires,
    Score,
    candidates,
    choose,
    eligible,
    soonest,
)
from ml_stack.fleet.rates import Rates
from ml_stack.fleet.remote import Peer, PeerError, sha256_file
from ml_stack.fleet.work import Placement, Unit, run

__all__ = [
    "BENCH_KIND",
    "MIN_PASSPHRASE",
    "REPORT_GROUP",
    "Advertiser",
    "Beacon",
    "Candidate",
    "DaemonError",
    "DiscoveryError",
    "Job",
    "JobRunner",
    "Peer",
    "PeerError",
    "Placement",
    "Rates",
    "Requires",
    "Score",
    "Unit",
    "calibrate",
    "candidates",
    "choose",
    "create_cluster_key",
    "derive_token",
    "device_report",
    "discover",
    "eligible",
    "check_passphrase",
    "cluster_group",
    "group_path",
    "in_cluster",
    "join_cluster",
    "key_from_passphrase",
    "key_path",
    "load_cluster_key",
    "load_or_create_token",
    "make_handler",
    "measure",
    "registered_reports",
    "resolve_report",
    "run",
    "safe_relpath",
    "serve_forever",
    "sha256_file",
    "soonest",
    "stdlib_device_report",
]
